spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: luvsic
    password: 123456
    virtual-host: test
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true